spring:
    datasource:
        url: jdbc:mysql://localhost:3306/libreria_spring
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialec: org.hibernate.dialec.MySQL8Dialec
    mvc:
        format:
            date: yyyy-MM-dd
